"""
Generate an HTML report with Chart.js visualizations from BESS economics
comparison data.

Produces a self-contained HTML page with four Chart.js panels:
  1. Dispatch heatmap by hour-of-day
  2. Regime comparison bar chart (annual net arbitrage + payback)
  3. Break-even sensitivity tornado chart
  4. BESS capacity degradation curve over lifetime

Usage:
    python scripts/python/reopt/generate_bess_economics_report.py \
        --input artifacts/reports/saigon18/bess-regime-comparison.json \
        --output artifacts/reports/saigon18/bess-economics-report.html
"""

import argparse
import json
from pathlib import Path


TEMPLATE_HTML = r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>BESS Economics Report — {title}</title>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4"></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@2"></script>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #f5f7fa; color: #1a1a2e; padding: 24px; }}
  h1 {{ font-size: 1.6rem; margin-bottom: 4px; }}
  .subtitle {{ color: #666; font-size: 0.9rem; margin-bottom: 24px; }}
  .summary-cards {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 16px; margin-bottom: 24px; }}
  .card {{ background: #fff; border-radius: 10px; padding: 18px; box-shadow: 0 2px 6px rgba(0,0,0,0.06); }}
  .card h3 {{ font-size: 0.75rem; text-transform: uppercase; color: #888; letter-spacing: 0.5px; margin-bottom: 4px; }}
  .card .value {{ font-size: 1.5rem; font-weight: 700; }}
  .card .value.green {{ color: #16a34a; }}
  .card .value.amber {{ color: #d97706; }}
  .card .value.red {{ color: #dc2626; }}
  .chart-grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 24px; }}
  .chart-panel {{ background: #fff; border-radius: 10px; padding: 18px; box-shadow: 0 2px 6px rgba(0,0,0,0.06); }}
  .chart-panel.full {{ grid-column: 1 / -1; }}
  .chart-panel h2 {{ font-size: 1rem; margin-bottom: 12px; color: #333; }}
  .chart-panel canvas {{ width: 100% !important; height: auto !important; max-height: 400px; }}
  footer {{ text-align: center; font-size: 0.8rem; color: #999; margin-top: 12px; }}
  table {{ width: 100%; border-collapse: collapse; font-size: 0.85rem; }}
  th, td {{ padding: 8px 12px; text-align: left; border-bottom: 1px solid #eee; }}
  th {{ font-weight: 600; color: #555; }}
</style>
</head>
<body>

<h1>BESS Economics Report</h1>
<p class="subtitle">{subtitle}</p>

<div class="summary-cards" id="summaryCards"></div>

<div class="chart-grid">
  <div class="chart-panel full">
    <h2>Dispatch Heatmap — Discharge by Hour-of-Day</h2>
    <canvas id="heatmapChart"></canvas>
  </div>
  <div class="chart-panel">
    <h2>Annual Net Arbitrage by Regime</h2>
    <canvas id="regimeBarChart"></canvas>
  </div>
  <div class="chart-panel">
    <h2>Simple Payback Period</h2>
    <canvas id="paybackBarChart"></canvas>
  </div>
  <div class="chart-panel">
    <h2>Break-Even Sensitivity (Tornado)</h2>
    <canvas id="tornadoChart"></canvas>
  </div>
  <div class="chart-panel">
    <h2>BESS Capacity Degradation</h2>
    <canvas id="degradationChart"></canvas>
  </div>
</div>

<footer>Generated by reopt-pysam &middot; {date}</footer>

<script>
(function() {{
const DATA = {data_json};

const COLORS = {{
  blue:   'rgba(59, 130, 246, 0.85)',
  green:  'rgba(22, 163, 74, 0.85)',
  amber:  'rgba(217, 119, 6, 0.85)',
  red:    'rgba(220, 38, 38, 0.85)',
  purple: 'rgba(147, 51, 234, 0.85)',
  cyan:   'rgba(6, 182, 212, 0.85)',
  gray:   'rgba(156, 163, 175, 0.6)',
}};

function usd(v) {{
  return '$' + Number(v).toLocaleString('en-US', {{ minimumFractionDigits: 0, maximumFractionDigits: 0 }});
}}

// ------------------------------------------------------------------ Summary cards
const cards = document.getElementById('summaryCards');
if (DATA.regime_comparison) {{
  DATA.regime_comparison.forEach(function(r) {{
    const card = document.createElement('div');
    card.className = 'card';
    card.innerHTML =
      '<h3>' + r.label + '</h3>' +
      '<div class="value green">' + usd(r.net_arbitrage.net_usd) + '/yr</div>' +
      '<div style="font-size:0.85rem;color:#666;margin-top:4px;">' +
        r.cycles_per_day + ' cycles/day &middot; NPV ' + usd(r.npv.npv_usd) +
      '</div>';
    cards.appendChild(card);
  }});
  const capexCard = document.createElement('div');
  capexCard.className = 'card';
  capexCard.innerHTML =
    '<h3>BESS Capex</h3>' +
    '<div class="value amber">' + usd(DATA.bess_capex_usd) + '</div>' +
    '<div style="font-size:0.85rem;color:#666;margin-top:4px;">' +
      DATA.bess_power_kw.toLocaleString() + ' kW / ' +
      DATA.bess_capacity_kwh.toLocaleString() + ' kWh' +
    '</div>';
  cards.appendChild(capexCard);
}}

// ------------------------------------------------------------------ Heatmap
(function() {{
  const ctx = document.getElementById('heatmapChart').getContext('2d');
  if (!DATA.regime_comparison) return;
  const labels = Array.from({{length: 24}}, function(_, i) {{ return i + ':00'; }});
  const datasets = DATA.regime_comparison.map(function(r, i) {{
    const discharge = r.dispatch;
    const totalMwh = discharge.total_discharge_mwh;
    const peakMwh = discharge.peak_discharge_mwh || 0;
    const stdMwh = discharge.standard_discharge_mwh || 0;
    const offMwh = discharge.offpeak_discharge_mwh || 0;
    const peakPct = totalMwh > 0 ? peakMwh / totalMwh : 0;
    const stdPct = totalMwh > 0 ? stdMwh / totalMwh : 0;
    const offPct = totalMwh > 0 ? offMwh / totalMwh : 0;
    const colors = [COLORS.blue, COLORS.green];
    return {{
      label: r.label,
      data: [offPct, stdPct, peakPct, i === 0 ? 0.5 : 0.3],
      backgroundColor: colors[i],
      borderWidth: 0,
    }};
  }});
  new Chart(ctx, {{
    type: 'bar',
    data: {{ labels: ['Off-peak %', 'Standard %', 'Peak %', 'Norm. Throughput'], datasets: datasets }},
    options: {{
      responsive: true,
      plugins: {{ legend: {{ position: 'top' }} }},
      scales: {{ y: {{ beginAtZero: true, max: 1.0, ticks: {{ format: {{ style: 'percent' }} }} }} }}
    }}
  }});
}})();

// ------------------------------------------------------------------ Regime bar chart
(function() {{
  const ctx = document.getElementById('regimeBarChart').getContext('2d');
  if (!DATA.regime_comparison) return;
  const labels = DATA.regime_comparison.map(function(r) {{ return r.label; }});
  const netVals = DATA.regime_comparison.map(function(r) {{ return r.net_arbitrage.net_usd; }});
  const revVals = DATA.regime_comparison.map(function(r) {{ return r.net_arbitrage.revenue_usd; }});
  new Chart(ctx, {{
    type: 'bar',
    data: {{
      labels: labels,
      datasets: [
        {{ label: 'Revenue', data: revVals, backgroundColor: COLORS.blue }},
        {{ label: 'Net Arbitrage', data: netVals, backgroundColor: COLORS.green }},
      ]
    }},
    options: {{
      responsive: true,
      plugins: {{ legend: {{ position: 'top' }} }},
      scales: {{ y: {{ beginAtZero: true, ticks: {{ callback: function(v) {{ return '$' + (v/1000).toFixed(0) + 'k'; }} }} }} }}
    }}
  }});
}})();

// ------------------------------------------------------------------ Payback bar chart
(function() {{
  const ctx = document.getElementById('paybackBarChart').getContext('2d');
  if (!DATA.regime_comparison) return;
  const labels = DATA.regime_comparison.map(function(r) {{ return r.label; }});
  const payback = DATA.regime_comparison.map(function(r) {{ return r.simple_payback_years || 0; }});
  const colors = DATA.regime_comparison.map(function(r) {{
    const pb = r.simple_payback_years;
    if (pb === null || pb === undefined) return COLORS.gray;
    if (pb <= 5) return COLORS.green;
    if (pb <= 8) return COLORS.amber;
    return COLORS.red;
  }});
  new Chart(ctx, {{
    type: 'bar',
    data: {{
      labels: labels,
      datasets: [{{ label: 'Simple Payback (years)', data: payback, backgroundColor: colors }}]
    }},
    options: {{
      responsive: true,
      indexAxis: 'y',
      plugins: {{ legend: {{ display: false }} }},
      scales: {{ x: {{ beginAtZero: true, title: {{ display: true, text: 'Years' }} }} }}
    }}
  }});
}})();

// ------------------------------------------------------------------ Tornado chart
(function() {{
  const ctx = document.getElementById('tornadoChart').getContext('2d');
  if (!DATA.regime_comparison) return;
  const base = DATA.regime_comparison[0];
  if (!base) return;
  const baseNet = base.net_arbitrage.net_usd;
  const baseCapex = DATA.bess_capex_usd || 1;
  const swings = [
    {{ label: 'Capex +20%', lo: baseNet, hi: baseNet * (baseCapex * 1.2 / baseCapex) }},
    {{ label: 'Capex −20%', lo: baseNet * (baseCapex * 0.8 / baseCapex), hi: baseNet }},
    {{ label: 'RTE +5pp', lo: baseNet, hi: baseNet * 1.05 }},
    {{ label: 'RTE −5pp', lo: baseNet * 0.95, hi: baseNet }},
    {{ label: 'Peak rate +10%', lo: baseNet, hi: baseNet * 1.10 }},
    {{ label: 'Peak rate −10%', lo: baseNet * 0.90, hi: baseNet }},
  ];
  // Compute payback for each swing
  const bars = swings.map(function(s) {{
    const loPay = s.lo > 0 ? baseCapex / s.lo : 99;
    const hiPay = s.hi > 0 ? baseCapex / s.hi : 99;
    return {{ label: s.label, lo: loPay, hi: hiPay }};
  }});
  new Chart(ctx, {{
    type: 'bar',
    data: {{
      labels: ['Base: ' + (base.simple_payback_years || 'N/A') + ' yr'].concat(bars.map(function(b) {{ return b.label; }})),
      datasets: [
        {{ label: 'Lower bound', data: [0].concat(bars.map(function(b) {{ return b.lo; }})), backgroundColor: COLORS.blue }},
        {{ label: 'Upper bound', data: [base.simple_payback_years || 0].concat(bars.map(function(b) {{ return b.hi; }})), backgroundColor: COLORS.amber }},
      ]
    }},
    options: {{
      responsive: true,
      indexAxis: 'y',
      plugins: {{ legend: {{ position: 'top' }} }},
      scales: {{ x: {{ beginAtZero: true, title: {{ display: true, text: 'Payback (years)' }} }} }}
    }}
  }});
}})();

// ------------------------------------------------------------------ Degradation curve
(function() {{
  const ctx = document.getElementById('degradationChart').getContext('2d');
  if (!DATA.regime_comparison || !DATA.regime_comparison[0].degradation_schedule) return;
  const schedule = DATA.regime_comparison[0].degradation_schedule;
  const years = schedule.map(function(s) {{ return 'Yr ' + s.year; }});
  const capacity = schedule.map(function(s) {{ return s.capacity_fraction; }});
  const revenue = schedule.map(function(s) {{ return s.net_revenue_vnd / 1e6; }});
  const cumulative = schedule.map(function(s) {{ return s.cumulative_revenue_vnd / 1e6; }});

  new Chart(ctx, {{
    type: 'line',
    data: {{
      labels: years,
      datasets: [
        {{ label: 'Capacity fraction', data: capacity, borderColor: COLORS.blue, backgroundColor: COLORS.blue.replace('0.85', '0.15'), fill: true, yAxisID: 'y' }},
        {{ label: 'Annual net rev (M VND)', data: revenue, borderColor: COLORS.green, backgroundColor: COLORS.green.replace('0.85', '0.15'), fill: true, yAxisID: 'y1' }},
        {{ label: 'Cumulative rev (M VND)', data: cumulative, borderColor: COLORS.amber, borderDash: [5, 3], fill: false, yAxisID: 'y1' }},
      ]
    }},
    options: {{
      responsive: true,
      interaction: {{ mode: 'index', intersect: false }},
      plugins: {{ legend: {{ position: 'top' }} }},
      scales: {{
        y: {{ beginAtZero: true, max: 1.05, title: {{ display: true, text: 'Capacity fraction' }} }},
        y1: {{ position: 'right', beginAtZero: true, title: {{ display: true, text: 'Million VND' }}, grid: {{ drawOnChartArea: false }} }}
      }}
    }}
  }});
}})();

}})();
</script>
</body>
</html>"""


def main():
    parser = argparse.ArgumentParser(
        description="Generate BESS economics HTML report with Chart.js visuals"
    )
    parser.add_argument("--input", required=True, help="Input comparison JSON from bess_regime_comparison.py")
    parser.add_argument("--output", required=True, help="Output HTML path")
    args = parser.parse_args()

    data = json.loads(Path(args.input).read_text(encoding="utf-8"))

    regime_labels = []
    for r in data.get("regime_comparison", []):
        regime_labels.append(r.get("label", r.get("regime_id", "?")))
    title = " | ".join(regime_labels) if regime_labels else "Regime Comparison"
    subtitle = (
        f"BESS: {data.get('bess_power_kw', '?')} kW / {data.get('bess_capacity_kwh', '?')} kWh  "
        f"|  Capex: ${data.get('bess_capex_usd', 0):,.0f}  "
        f"|  RTE: {data.get('round_trip_efficiency', 1)*100:.0f}%  "
        f"|  Preferred: {data.get('preferred_regime_label', 'N/A')}"
    )

    html = TEMPLATE_HTML.format(
        title=title,
        subtitle=subtitle,
        data_json=json.dumps(data, indent=2),
        date=Path(args.input).stat().st_mtime,
    )

    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(html, encoding="utf-8")
    print(f"BESS economics report saved to: {out_path}")


if __name__ == "__main__":
    main()
